title: "Titel"
size: 9
items:
  '1':
    action: RESET # RESET, GRAY_FADE_EFFECT, RAINBOW_EFFECT, RANDOM_EFFECT, NONE
    type: "BARRIER:0"
    name: "RESET"
    lore:
      - "cos"
  '2':
    action: GRAY_FADE_EFFECT
    type: "BARRIER:0"
    name: "GRAYFADE"
    lore:
      - "cos"
  '3':
    action: RAINBOW_EFFECT
    type: "BARRIER:0"
    name: "RAINBOW"
    lore:
      - "cos"
  '4':
    action: RANDOM_EFFECT
    type: "BARRIER:0"
    name: "RANDOM"
    lore:
      - "cos"
  '5':
    action: NONE
    type: "BARRIER:0"
    name: "RANDOM"
    lore:
      - "cos"